### PR TITLE
Remove Nuget.config

### PR DESCRIPTION
**Pull request by suhasj**
@sayedihashimi 

Removed the Nuget.config from the generator since the bits are now available on Nuget

### CODE REVIEW

**Comment by sayedihashimi** [comment]
I've merged it to Release and published as `0.0.12`. Can you update your generators and verify that we are still good? I'm doing that now as well.

Can we automate this? We already have [travis hooked up](https://travis-ci.org/ligershark/generator-aspnet)? I'll open an issue to discuss.

**Comment by sayedihashimi** [comment]
@suhasj what about `global.json`? Now that we've removed `nuget.config` I think we should remove `global.json` as well. It was only there for `kpm restore` to look for `nuget.config`.

**Comment by suhasj** [comment]
-  I’ll send a separate PR to remove the global.config. Yes we might not need it any more.
-  I updated the generator on Mac and tested out the template. They work fine with beta bits.
-  I don’t have much expertise on Travis build but let me know how I can help with it.

**Comment by sayedihashimi** [comment]
Thanks @suhasj.

Regarding Travis I've asked if @kenwarner can help here. He is more familiar with Travis and is passionate about the ASP.NET 5 + yo.

@kenwarner thanks a lot for helping us get out story straight!

**Pull request merged**
